---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClassClaim
metadata:
  name: mysql
  namespace: cdelashmutt
spec:
  classRef:
    name: mysql
  parameters:
    parameters:
      size: small
